variable "aws_region" {}
variable "az" {}
variable "ebs_size" {}
variable "ami_id" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "key_name" {}
variable "bucket_name" {}
variable "bucket_path" {}
